// packages/frontend-react/src/App.tsx
import { useEffect, useRef, useCallback } from "react";
import type { Core } from "cytoscape";
import { useUiState, useUiDispatch } from "./store/ui.tsx";
import { DetailsPanel } from "./components/DetailsPanel.tsx";
import { SettingsPanel } from "./components/SettingsPanel.tsx";
import { drawGraph, destroyGraph } from "./graph/graph.ts";
import {
  applyNodeStyle,
  highlightNeighborhood,
  resetHighlight,
} from "./graph/graph-style.ts";
import {
  type GraphInstance,
  Layouts,
  Renderers,
  Themes,
} from "./graph/graph-types.ts";
import { openNode } from "./graph/node.ts";

function App() {
  const state = useUiState();
  const dispatch = useUiDispatch();
  const {
    theme,
    renderer,
    layout,
    nodeSize,
    labelScale,
    showLabels,
    settingsOpen,
    detailsOpen,
    selected,
  } = state;

  const graphRef = useRef<HTMLDivElement>(null);
  const graphInstanceRef = useRef<GraphInstance | undefined>(undefined);

  const openNodeAction = useCallback(async (nodeId: string) => {
    const node = await openNode(theme, nodeId);
    dispatch({ type: "SET_STATE", payload: { selected: node } });
    dispatch({ type: "OPEN_DETAILS" });
  }, [theme, dispatch]);

  const bindGraphEvents = useCallback(() => {
    const graph = graphInstanceRef.current;
    if (!graph) return;

    if (renderer === "cytoscape") {
      const cy = graph as Core;
      cy.off("tap", "node");
      cy.on("tap", "node", (evt) => {
        void openNodeAction(evt.target.id());
      });
    } else {
      interface ClickableGraph {
        onNodeClick(cb: (node: { id: string }) => void): void;
      }
      const fg = graph as ClickableGraph;
      fg.onNodeClick((node: { id: string }) => {
        void openNodeAction(node.id);
      });
    }
  }, [renderer, openNodeAction]);

  const refreshGraph = useCallback(async () => {
    if (!graphRef.current) return;
    graphInstanceRef.current = await drawGraph(
      renderer,
      layout,
      graphRef.current,
      graphInstanceRef.current,
      nodeSize,
      labelScale,
      showLabels
    );
    bindGraphEvents();
  }, [renderer, layout, nodeSize, labelScale, showLabels, bindGraphEvents]);

  const closeDetails = () => {
    dispatch({ type: "CLOSE_DETAILS" });
    resetHighlight(graphInstanceRef.current);
  };

  const toggleDetails = () => {
    if (detailsOpen) {
      closeDetails();
    } else {
      dispatch({ type: "OPEN_DETAILS" });
      if (selected.id) {
        highlightNeighborhood(graphInstanceRef.current, selected.id);
      }
    }
  };

  useEffect(() => {
    refreshGraph();

    return () => {
      if (graphRef.current) {
        destroyGraph(graphInstanceRef.current, graphRef.current);
        graphInstanceRef.current = undefined;
      }
    };
  }, [renderer, refreshGraph]);

  useEffect(() => {
    refreshGraph();
  }, [theme, showLabels, layout]);

  useEffect(() => {
    if (renderer === "cytoscape") {
      applyNodeStyle(graphInstanceRef.current as Core, {
        width: nodeSize,
        height: nodeSize,
      });
    } else {
      refreshGraph();
    }
  }, [nodeSize, renderer, refreshGraph]);

  useEffect(() => {
    if (renderer === "cytoscape") {
      applyNodeStyle(graphInstanceRef.current as Core, {
        "font-size": `${labelScale}em`,
      });
    } else {
      refreshGraph();
    }
  }, [labelScale, renderer, refreshGraph]);

  useEffect(() => {
    if (detailsOpen && selected.id) {
        highlightNeighborhood(graphInstanceRef.current, selected.id);
    }
  }, [detailsOpen, selected.id])

  return (
    <div className="vh-100 vw-100">
      <div ref={graphRef} className="h-100 w-100" />

      <SettingsPanel
        open={settingsOpen}
        themes={Themes}
        renderers={Renderers}
        layouts={Layouts}
        theme={theme}
        renderer={renderer}
        layout={layout}
        nodeSize={nodeSize}
        labelScale={labelScale}
        showLabels={showLabels}
        onThemeChange={(t) => dispatch({ type: "SET_STATE", payload: { theme: t } })}
        onRendererChange={(r) => dispatch({ type: "SET_STATE", payload: { renderer: r } })}
        onLayoutChange={(l) => dispatch({ type: "SET_STATE", payload: { layout: l } })}
        onNodeSizeChange={(s) => dispatch({ type: "SET_STATE", payload: { nodeSize: s } })}
        onLabelScaleChange={(s) => dispatch({ type: "SET_STATE", payload: { labelScale: s } })}
        onShowLabelsChange={(s) => dispatch({ type: "SET_STATE", payload: { showLabels: s } })}
        onClose={() => dispatch({ type: "TOGGLE_SETTINGS" })}
      />

      <button
        type="button"
        className="btn btn-outline-secondary position-fixed"
        style={{ top: "1rem", left: "1rem", zIndex: 1 }}
        onClick={() => dispatch({ type: "TOGGLE_SETTINGS" })}
      >
        <i className="bi bi-gear"></i>
      </button>

      <DetailsPanel
        theme={theme}
        selected={selected}
        open={detailsOpen}
        onClose={closeDetails}
        onOpenNode={openNodeAction}
      />

      <button
        type="button"
        className="btn btn-outline-secondary position-fixed"
        style={{ top: "1rem", right: "1rem", zIndex: 1 }}
        onClick={toggleDetails}
      >
        <i className="bi bi-chevron-left"></i>
      </button>
    </div>
  );
}

export default App;

// packages/frontend/src/App.vue
<template>
  <div class="vh-100 vw-100">
    <div ref="graphRef" class="h-100 w-100"></div>

    <SettingsPanel
      v-model:theme="theme"
      v-model:renderer="renderer"
      v-model:layout="layout"
      v-model:node-size="nodeSize"
      v-model:label-scale="labelScale"
      v-model:show-labels="showLabels"
      :open="settingsOpen"
      :themes="themes"
      :renderers="renderers"
      :layouts="layouts"
      @update:layout="setLayout"
      @close="store.toggleSettings()"
    />

    <button
      type="button"
      class="btn btn-outline-secondary position-fixed"
      style="top: 1rem; left: 1rem; z-index: 1"
      @click="toggleSettings"
    >
      <i class="bi bi-gear"></i>
    </button>

    <DetailsPanel
      :theme="theme"
      :selected="selected"
      :open="detailsOpen"
      @close="closeDetails"
      @open-node="openNodeAction"
    />

    <button
      type="button"
      class="btn btn-outline-secondary position-fixed"
      style="top: 1rem; right: 1rem; z-index: 1"
      @click="toggleDetails"
    >
      <i class="bi bi-chevron-left"></i>
    </button>
  </div>
</template>

<script setup lang="ts">
import type { Core } from "cytoscape";
import { storeToRefs } from "pinia";
import { onMounted, ref, watch } from "vue";
import { useUiStore } from "./store.ts";
import DetailsPanel from "./components/DetailsPanel.vue";
import SettingsPanel from "./components/SettingsPanel.vue";
import { drawGraph } from "./graph.ts";
import {
  applyNodeStyle,
  highlightNeighborhood,
  resetHighlight,
} from "./graph-style.ts";
import {
  type GraphInstance,
  type Layout,
  Layouts,
  Renderers,
  Themes,
} from "./graph-types.ts";
import { openNode } from "./node.ts";

void SettingsPanel;
void DetailsPanel;

const themes = Themes;
const layouts = Layouts;
const renderers = Renderers;
const graph = ref<GraphInstance>();
const graphRef = ref<HTMLElement>();
const store = useUiStore();
const {
  theme,
  renderer,
  layout,
  nodeSize,
  labelScale,
  showLabels,
  settingsOpen,
  detailsOpen,
  selected,
} = storeToRefs(store);

function bindGraphEvents(): void {
  if (!graph.value) return;
  if (renderer.value === "cytoscape") {
    const cy = graph.value as Core;
    cy.off("tap", "node");
    cy.on("tap", "node", ({ target }) => {
      void openNodeAction(target.id());
    });
  } else {
    interface ClickableGraph {
      onNodeClick(cb: (node: { id: string }) => void): void;
    }
    const fg = graph.value as ClickableGraph;
    fg.onNodeClick((node: { id: string }) => {
      void openNodeAction(node.id);
    });
  }
}

/**
 * Initialize the application and render the graph.
 */
async function init(): Promise<void> {
  graph.value = await drawGraph(
    renderer.value,
    layout.value,
    graphRef.value as HTMLElement,
    graph.value,
    nodeSize.value,
    labelScale.value,
    showLabels.value,
  );
  bindGraphEvents();
}

/**
 * Re-render the graph with current settings.
 */
async function refresh(): Promise<void> {
  graph.value = await drawGraph(
    renderer.value,
    layout.value,
    graphRef.value as HTMLElement,
    graph.value,
    nodeSize.value,
    labelScale.value,
    showLabels.value,
  );
  bindGraphEvents();
}

/** Change layout and refresh the graph. */
function setLayout(newLayout: Layout): void {
  store.layout = newLayout;
  void refresh();
}

/** Fetch and display details for node ID. */
async function openNodeAction(nodeId: string): Promise<void> {
  const node = await openNode(theme.value, nodeId);
  selected.value = node;
  openDetails();
}

/** Show the details pane and dim other nodes. */
function openDetails(): void {
  store.openDetails();
  highlightNeighborhood(graph.value, selected.value.id);
}

/** Hide the details pane and restore styles. */
function closeDetails(): void {
  store.closeDetails();
  resetHighlight(graph.value);
}

/** Toggle the details pane. */
function toggleDetails(): void {
  if (detailsOpen.value) {
    closeDetails();
  } else {
    openDetails();
  }
}

/** Toggle the settings pane. */
function toggleSettings(): void {
  store.toggleSettings();
}

watch(renderer, () => {
  graph.value = undefined;
  void refresh();
});
watch(theme, () => {
  void refresh();
});
watch(nodeSize, (value) => {
  if (renderer.value === "cytoscape")
    applyNodeStyle(graph.value as Core, {
      width: value,
      height: value,
    });
  else void refresh();
});

watch(labelScale, (value) => {
  if (renderer.value === "cytoscape")
    applyNodeStyle(graph.value as Core, {
      "font-size": `${value}em`,
    });
  else void refresh();
});

watch(showLabels, () => {
  void refresh();
});
onMounted(init);
</script>
