// packages/frontend/src/app.tsx
import type { Core } from "cytoscape";
import { useEffect, useRef, useState } from "react";
import { Button, Form, Offcanvas } from "react-bootstrap";
import { createRoot } from "react-dom/client";
import {
	BrowserRouter,
	Route,
	Routes,
	useNavigate,
	useParams,
} from "react-router";
import type { components } from "./api.d.ts";
import {
	dimOthers,
	type Layout,
	Layouts,
	openNode,
	renderGraph,
	setElementsStyle,
	type Theme,
	Themes,
} from "./util.ts";

type NodeData = components["schemas"]["Node"] & { html?: string };

function GraphView({
	layout,
	theme,
	nodeSize,
	labelScale,
	onOpenNode,
	onGraphReady,
}: {
	layout: Layout;
	theme: Theme;
	nodeSize: number;
	labelScale: number;
	onOpenNode: (id: string) => void;
	onGraphReady: (g: Core) => void;
}) {
	const containerRef = useRef<HTMLDivElement>(null);
	const graphRef = useRef<Core | undefined>(undefined);
	const onOpenNodeRef = useRef(onOpenNode);

	useEffect(() => {
		onOpenNodeRef.current = onOpenNode;
	}, [onOpenNode]);

	useEffect(() => {
		const _theme = theme;
		const container = containerRef.current;
		if (!container) return;
		let mounted = true;
		void renderGraph(
			layout,
			container,
			graphRef.current,
			nodeSize,
			labelScale,
		).then((g) => {
			if (!mounted) return;
			graphRef.current = g;
			g.off("tap");
			g.on("tap", "node", ({ target }) => onOpenNodeRef.current(target.id()));
			onGraphReady(g);
		});
		return () => {
			mounted = false;
		};
	}, [layout, nodeSize, labelScale, onGraphReady, theme]);

	return <div ref={containerRef} id="graph" className="h-100 w-100"></div>;
}

function NodeDetails({
	id,
	theme,
	onClose,
	onOpenNode,
	graph,
}: {
	id?: string;
	theme: Theme;
	onClose: () => void;
	onOpenNode: (id: string) => void;
	graph: Core | undefined;
}) {
	const [node, setNode] = useState<NodeData | null>(null);
	useEffect(() => {
		if (!id) return;
		void openNode(theme, id).then((n) => setNode(n));
	}, [id, theme]);

	useEffect(() => {
		if (!id) return;
		dimOthers(graph, id);
		return () => {
			setElementsStyle(graph, { opacity: 1 });
		};
	}, [id, graph]);

	return (
		<Offcanvas
			show={Boolean(id)}
			onHide={onClose}
			placement="end"
			className="responsive-wide"
		>
			<Offcanvas.Header closeButton>
				<Offcanvas.Title>
					<i className="bi bi-file-earmark-text"></i> {node?.title ?? ""}
				</Offcanvas.Title>
			</Offcanvas.Header>
			<Offcanvas.Body>
				{/* biome-ignore lint/security/noDangerouslySetInnerHtml: html is sanitized on the server */}
				<div dangerouslySetInnerHTML={{ __html: node?.html ?? "" }} />
				{node?.backlinks?.length ? (
					<div className="mt-3">
						<h5>
							<i className="bi bi-link-45deg"></i>Backlinks
						</h5>
						<ul className="list-unstyled">
							{node.backlinks.map((b) => (
								<li key={b.source}>
									<Button
										variant="link"
										className="btn-sm p-0"
										onClick={() => onOpenNode(b.source)}
									>
										<i className="bi bi-chevron-right"></i> {b.title}
									</Button>
								</li>
							))}
						</ul>
					</div>
				) : null}
			</Offcanvas.Body>
		</Offcanvas>
	);
}

function Settings({
	show,
	onHide,
	theme,
	setTheme,
	layout,
	setLayout,
	nodeSize,
	setNodeSize,
	labelScale,
	setLabelScale,
}: {
	show: boolean;
	onHide: () => void;
	theme: Theme;
	setTheme: (t: Theme) => void;
	layout: Layout;
	setLayout: (l: Layout) => void;
	nodeSize: number;
	setNodeSize: (n: number) => void;
	labelScale: number;
	setLabelScale: (n: number) => void;
}) {
	return (
		<Offcanvas show={show} onHide={onHide} placement="start">
			<Offcanvas.Header closeButton>
				<Offcanvas.Title>
					<i className="bi bi-gear-fill"></i>Settings
				</Offcanvas.Title>
			</Offcanvas.Header>
			<Offcanvas.Body>
				<Form.Group className="mb-4">
					<Form.Label>Theme</Form.Label>
					<Form.Select
						value={theme}
						onChange={(e) => setTheme(e.target.value as Theme)}
					>
						{Themes.map((t) => (
							<option key={t.value} value={t.value}>
								{t.label}
							</option>
						))}
					</Form.Select>
				</Form.Group>
				<Form.Group className="mb-4">
					<Form.Label>Layout</Form.Label>
					<Form.Select
						value={layout}
						onChange={(e) => setLayout(e.target.value as Layout)}
					>
						{Layouts.map((l) => (
							<option key={l} value={l}>
								{l}
							</option>
						))}
					</Form.Select>
				</Form.Group>
				<Form.Group className="mb-4">
					<Form.Label>Node size</Form.Label>
					<Form.Range
						min={5}
						max={30}
						value={nodeSize}
						onChange={(e) => setNodeSize(Number(e.target.value))}
					/>
				</Form.Group>
				<Form.Group className="mb-4">
					<Form.Label>Font size</Form.Label>
					<Form.Range
						min={0.3}
						max={1.5}
						step={0.1}
						value={labelScale}
						onChange={(e) => setLabelScale(Number(e.target.value))}
					/>
				</Form.Group>
			</Offcanvas.Body>
		</Offcanvas>
	);
}

function Main() {
	const [theme, setTheme] = useState<Theme>(
		matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light",
	);
	const [layout, setLayout] = useState<Layout>("cose");
	const [nodeSize, setNodeSize] = useState(10);
	const [labelScale, setLabelScale] = useState(0.5);
	const [showSettings, setShowSettings] = useState(false);
	const [graph, setGraph] = useState<Core>();
	const navigate = useNavigate();
	const { id } = useParams<{ id?: string }>();
	const openNodes = useRef<string[]>([]);

	useEffect(() => {
		if (id && !openNodes.current.includes(id)) openNodes.current.push(id);
	}, [id]);

	useEffect(() => {
		document.documentElement.setAttribute("data-theme", theme);
		document.documentElement.setAttribute(
			"data-bs-theme",
			theme.replace(/.*-/, ""),
		);
	}, [theme]);

	const handleOpenNode = (nodeId: string) => navigate(`/node/${nodeId}`);

	return (
		<>
			<GraphView
				theme={theme}
				layout={layout}
				nodeSize={nodeSize}
				labelScale={labelScale}
				onOpenNode={handleOpenNode}
				onGraphReady={setGraph}
			/>
			<Button
				variant="outline-secondary"
				style={{ position: "fixed", top: "1rem", left: "1rem", zIndex: 1 }}
				onClick={() => setShowSettings(true)}
			>
				<i className="bi bi-gear"></i>
			</Button>
			<Settings
				show={showSettings}
				onHide={() => setShowSettings(false)}
				theme={theme}
				setTheme={setTheme}
				layout={layout}
				setLayout={setLayout}
				nodeSize={nodeSize}
				setNodeSize={setNodeSize}
				labelScale={labelScale}
				setLabelScale={setLabelScale}
			/>
			<NodeDetails
				id={id}
				theme={theme}
				graph={graph}
				onClose={() => navigate("/")}
				onOpenNode={handleOpenNode}
			/>
		</>
	);
}

export function App() {
	return (
		<BrowserRouter>
			<Routes>
				<Route path="/" element={<Main />} />
				<Route path="/node/:id" element={<Main />} />
			</Routes>
		</BrowserRouter>
	);
}

const container = document.getElementById("root");
if (container) createRoot(container).render(<App />);

export { Main };

// packages/frontend/src/App.vue
<template>
  <div class="vh-100 vw-100">
    <div ref="graphRef" class="h-100 w-100"></div>

    <SettingsPanel
      :open="settingsOpen"
      :themes="themes"
      :theme="theme"
      :renderers="renderers"
      :renderer="renderer"
      :layouts="layouts"
      :layout="layout"
      :node-size="nodeSize"
      :label-scale="labelScale"
      :show-labels="showLabels"
      @close="settingsOpen = false"
      @update:theme="setTheme"
      @update:renderer="setRenderer"
      @update:layout="setLayout"
      @update:node-size="onSizeChange"
      @update:label-scale="onScaleChange"
      @update:show-labels="onShowLabelsChange"
    />

    <button
      type="button"
      class="btn btn-outline-secondary position-fixed"
      style="top: 1rem; left: 1rem; z-index: 1"
      @click="toggleSettings"
    >
      <i class="bi bi-gear"></i>
    </button>

    <DetailsPanel
      :theme="theme"
      :selected="selected"
      :open="detailsOpen"
      @close="closeDetails"
      @open-node="openNodeAction"
    />

    <button
      type="button"
      class="btn btn-outline-secondary position-fixed"
      style="top: 1rem; right: 1rem; z-index: 1"
      @click="toggleDetails"
    >
      <i class="bi bi-chevron-left"></i>
    </button>
  </div>
</template>

<script setup lang="ts">
import type { Core } from "cytoscape";
import { onMounted, ref, type VNode, watch } from "vue";
import type { components } from "./api.d.ts";
import DetailsPanel from "./components/DetailsPanel.vue";
import SettingsPanel from "./components/SettingsPanel.vue";
import { drawGraph } from "./graph.ts";
import {
  applyNodeStyle,
  highlightNeighborhood,
  resetHighlight,
} from "./graph-style.ts";
import {
  type GraphInstance,
  type Layout,
  Layouts,
  type Renderer,
  Renderers,
  type Theme,
  Themes,
} from "./graph-types.ts";
import { openNode } from "./node.ts";

void SettingsPanel;
void DetailsPanel;

const themes = Themes;
const theme = ref<Theme>(
  matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light",
);
const nodeSize = ref(10);
const labelScale = ref(0.5);
const showLabels = ref(true);
const layout = ref<Layout>("cose");
const layouts = Layouts;
const renderers = Renderers;
const renderer = ref<Renderer>("force-graph");
const graph = ref<GraphInstance>();
const selected = ref<components["schemas"]["Node"] & { body?: VNode }>(
  {} as components["schemas"]["Node"] & { body?: VNode },
);
const settingsOpen = ref(false);
const detailsOpen = ref(false);
const graphRef = ref<HTMLElement>();

function bindGraphEvents(): void {
  if (!graph.value) return;
  if (renderer.value === "cytoscape") {
    const cy = graph.value as Core;
    cy.off("tap", "node");
    cy.on("tap", "node", ({ target }) => {
      void openNodeAction(target.id());
    });
  } else {
    interface ClickableGraph {
      onNodeClick(cb: (node: { id: string }) => void): void;
    }
    const fg = graph.value as ClickableGraph;
    fg.onNodeClick((node: { id: string }) => {
      void openNodeAction(node.id);
    });
  }
}

/**
 * Initialize the application and render the graph.
 */
async function init(): Promise<void> {
  graph.value = await drawGraph(
    renderer.value,
    layout.value,
    graphRef.value as HTMLElement,
    graph.value,
    nodeSize.value,
    labelScale.value,
    showLabels.value,
  );
  bindGraphEvents();
}

/**
 * Re-render the graph with current settings.
 */
async function refresh(): Promise<void> {
  graph.value = await drawGraph(
    renderer.value,
    layout.value,
    graphRef.value as HTMLElement,
    graph.value,
    nodeSize.value,
    labelScale.value,
    showLabels.value,
  );
  bindGraphEvents();
}

/** Change layout and refresh the graph. */
function setLayout(newLayout: Layout): void {
  layout.value = newLayout;
  void refresh();
}

/** Change renderer and refresh. */
function setRenderer(newRenderer: Renderer): void {
  renderer.value = newRenderer;
  graph.value = undefined;
}

/** Switch between themes and refresh. */
function setTheme(newTheme: Theme): void {
  theme.value = newTheme;
  void refresh();
}

/** Adjust node size in the graph. */
function onSizeChange(): void {
  if (renderer.value === "cytoscape")
    applyNodeStyle(graph.value as Core, {
      width: nodeSize.value,
      height: nodeSize.value,
    });
  else void refresh();
}

/** Adjust label scale in the graph. */
function onScaleChange(): void {
  if (renderer.value === "cytoscape")
    applyNodeStyle(graph.value as Core, {
      "font-size": `${labelScale.value}em`,
    });
  else void refresh();
}

/** Toggle label visibility. */
function onShowLabelsChange(): void {
  void refresh();
}

/** Fetch and display details for node ID. */
async function openNodeAction(nodeId: string): Promise<void> {
  const node = await openNode(theme.value, nodeId);
  selected.value = node;
  openDetails();
}

/** Show the details pane and dim other nodes. */
function openDetails(): void {
  detailsOpen.value = true;
  highlightNeighborhood(graph.value, selected.value.id);
}

/** Hide the details pane and restore styles. */
function closeDetails(): void {
  detailsOpen.value = false;
  resetHighlight(graph.value);
}

/** Toggle the details pane. */
function toggleDetails(): void {
  if (detailsOpen.value) {
    closeDetails();
  } else {
    openDetails();
  }
}

/** Toggle the settings pane. */
function toggleSettings(): void {
  settingsOpen.value = !settingsOpen.value;
}

watch(renderer, () => {
  graph.value = undefined;
  void refresh();
});

onMounted(init);

watch(
  theme,
  (value) => {
    const doc = document.documentElement;
    doc.setAttribute("data-bs-theme", value.replace(/.*-/, ""));
    doc.setAttribute("data-theme", value);
  },
  { immediate: true },
);
</script>
